---

- hosts: "{{ vm_prefix }}*"
  roles:
#    - redhat_sap.sap_rhsm # replace with rhn register step/role
    - redhat_sap.sap_hostagent

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "hsr_role/alias: {{ sap_hana_hsr_role }} / {{ sap_hana_hsr_alias }}"

  roles:
    - redhat_sap.sap_hana_deployment
    - redhat_sap.sap_hana_hsr
#    - redhat_sap.sap_hana_ha_pacemaker

  post_tasks:
    - name: prevent transaction log to fill up disk
      shell: >
        /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
        -n {{ ansible_hostname }} -i {{ sap_hana_deployment_hana_instance_number }}
        -u SYSTEM -p {{ sap_hana_deployment_hana_db_system_password }}
        "ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'overwrite' WITH RECONFIGURE";
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: db_overwrite_cmd
      failed_when: false
      when: sap_hana_hsr_role == 'primary'

    - debug:
        msg: "{{ db_overwrite_cmd }}"
      when: sap_hana_hsr_role == 'primary'

    - name: set primary hana server ip
      add_host:
        name: hana_primary
        ip_address: "{{ ansible_ip_addresses[0] | default(ansible_host) | default(ansible_ssh_host) }}"
      when: sap_hana_hsr_role == 'primary'

    - debug:
        var: hostvars['hana_primary']['ip_address']
      when: sap_hana_hsr_role == 'primary'

- hosts: "{{ vm_prefix }}*:&*s4_image"
  pre_tasks:
    - name: add temporary vip to hosts file for primary db
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ sap_db_host }}$'
        line: "{{ hostvars['hana_primary']['ip_address'] }} {{ sap_db_host }}.{{ foreman.domain_name }} {{ sap_db_host }}"
        state: present
      when: sap_db_host is defined
  roles:
    - sap_s4hana_deployment

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "hsr_role/alias: {{ sap_hana_hsr_role }} / {{ sap_hana_hsr_alias }}"

  roles:
    - redhat_sap.sap_hana_ha_pacemaker

  post_tasks:
    - block:
        - name: set to normal mode
          shell: >
            source /usr/sap/RHE/home/.sapenv.sh &&
            /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
            -n {{ ansible_hostname }} -i {{ sap_hana_deployment_hana_instance_number }}
            -u SYSTEM -p {{ sap_hana_deployment_hana_db_system_password }}
            "ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'normal') = 'overwrite' WITH RECONFIGURE";
          become: yes
          become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
          become_method: su
          register: db_overwrite_cmd
          failed_when: false

        - debug:
            msg: "{{ db_overwrite_cmd }}"

        - name: ensure backup exists
          shell: >
            source /usr/sap/RHE/home/.sapenv.sh &&
            /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
            -i {{ sap_hana_deployment_hana_instance_number }}
            -u SYSTEM -p {{ sap_hana_deployment_hana_db_system_password }}
            -d SYSTEMDB
            "BACKUP DATA FOR {{ sap_hana_deployment_hana_sid }} USING FILE ('data_bck')"
          become: yes
          become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
          become_method: su
          register: db_overwrite_cmd
          failed_when: false
      when: sap_hana_hsr_role == 'primary'

- hosts: "{{ vm_prefix }}*:&*s4_image"
  tasks:
    - name: add real vip to hosts file for db
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ sap_db_host }}$'
        line: "{{ sap_hana_ha_pacemaker_vip }} {{ sap_db_host }}.{{ foreman.domain_name }} {{ sap_db_host }}"
        state: present
      when:
        - sap_db_host is defined
        - sap_hana_ha_pacemaker_vip is defined