---

- hosts: "{{ vm_prefix }}*:&*hana_image"
  become_method: su
  pre_tasks:
    - debug:
        msg: "hsr_role/alias: {{ sap_hana_hsr_role }} / {{ sap_hana_hsr_alias }}"

  roles:
#    - redhat_sap.sap_rhsm # replace with rhn register step/role
    - redhat_sap.sap_hostagent
    - redhat_sap.sap_hana_deployment
    - redhat_sap.sap_hana_hsr
#    - redhat_sap.sap_hana_ha_pacemaker

  post_tasks:
    - name: prevent transaction log to fill up disk
      shell: >
        /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
        -n {{ ansible_hostname }} -i {{ sap_hana_deployment_hana_instance_number }}
        -u SYSTEM -p {{ sap_hana_deployment_hana_db_system_password }}
        "ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'log_mode') = 'overwrite' WITH RECONFIGURE";
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: db_overwrite_cmd
      failed_when: false
      when: sap_hana_hsr_role == 'primary'

    - debug:
        msg: "{{ db_overwrite_cmd }}"
      when: sap_hana_hsr_role == 'primary'